export const USER_GROUP = "USER";
export const ORG_GROUP = "ORG";
export const PARTNER_GROUP = "PARTNER";
export const AMBASADOR_GROUP = "AMBASADOR";

export const USER_GROUP_NUMBER = 11;
export const ORG_GROUP_NUMBER = 12;
export const PARTNER_GROUP_NUMBER = 13;
export const AMBASADOR_GROUP_NUMBER = 14;

export const groupMap = {
  [USER_GROUP_NUMBER]: USER_GROUP,
  [ORG_GROUP_NUMBER]: ORG_GROUP,
  [PARTNER_GROUP_NUMBER]: PARTNER_GROUP,
  [AMBASADOR_GROUP_NUMBER]: AMBASADOR_GROUP,
};

export const personEvents = {
  [USER_GROUP_NUMBER]: "SUBSCUBES",
  [PARTNER_GROUP_NUMBER]: "LINK_PARTNER",
};
